(function(){
'use strict';
const STORE='cc_floating_keyboard_v1';
const defaults={mode:'editor',compact:false,size:38,numberRow:true,haptic:true,custom:['undo','redo','save','run'],x:null,y:null};
const choices=[['undo','Urungkan'],['redo','Ulangi'],['save','Simpan'],['run','Jalankan'],['find','Cari'],['select','Pilih semua'],['copy','Salin'],['paste','Tempel'],['cut','Potong'],['comment','Komentar'],['duplicate','Duplikat baris'],['moveup','Baris ke atas'],['movedown','Baris ke bawah'],['clear','Bersihkan terminal'],['home','Home'],['end','End'],['tab','Tab'],['esc','Esc']];
const ACTIONS=Object.fromEntries(choices), shifted={'1':'!','2':'@','3':'#','4':'$','5':'%','6':'^','7':'&','8':'*','9':'(','0':')','-':'_','=':'+','[':'{',']':'}','\\':'|',';':':',"'":'"',',':'<','.':'>','/':'?','`':'~'};
let state={...defaults};
try{const saved=JSON.parse(localStorage.getItem(STORE)||'{}');if(saved&&typeof saved==='object')state={...state,...saved};}catch(e){}
state.custom=Array.isArray(state.custom)?defaults.custom.map((v,i)=>ACTIONS[state.custom[i]]?state.custom[i]:v):defaults.custom.slice();
const root=document.createElement('section');
root.id='floating-keyboard';root.setAttribute('aria-label','Keyboard layar');
root.innerHTML=`<div class="fk-head" id="fk-drag"><span class="fk-grip" aria-hidden="true">⠿</span><div class="fk-heading"><span class="fk-title">KEYBOARD</span><span class="fk-target" id="fk-target">EDITOR</span></div><div class="fk-spacer"></div><div class="fk-modes" role="group" aria-label="Tujuan keyboard"><button type="button" data-mode="editor">Editor</button><button type="button" data-mode="terminal">Terminal</button></div><button type="button" id="fk-settings-button" title="Atur keyboard" aria-label="Atur keyboard" aria-expanded="false">⚙</button><button type="button" id="fk-close" title="Tutup keyboard" aria-label="Tutup keyboard">✕</button></div><div class="fk-body" id="fk-keys"></div><div class="fk-settings" id="fk-settings"><div class="fk-setting-row"><label for="fk-size">Tinggi tombol</label><input id="fk-size" type="range" min="30" max="52" step="2"><span id="fk-size-label"></span></div><div class="fk-setting-row"><label for="fk-compact">Ringkas</label><input id="fk-compact" type="checkbox"></div><div class="fk-setting-row"><label for="fk-numbers">Baris angka</label><input id="fk-numbers" type="checkbox"></div><div class="fk-setting-row"><label for="fk-haptic">Getaran sentuh</label><input id="fk-haptic" type="checkbox"></div><div class="fk-setting-title">Tombol favorit</div><div class="fk-custom-grid" id="fk-custom"></div></div>`;
document.body.appendChild(root);
const keys=root.querySelector('#fk-keys');
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));}catch(e){}}
function clamp(n,min,max){return Math.max(min,Math.min(n,max));}
function bounds(){const vv=window.visualViewport;return{w:vv?vv.width:innerWidth,h:vv?vv.height:innerHeight,ox:vv?vv.offsetLeft:0,oy:vv?vv.offsetTop:0};}
function place(){const b=bounds(),r=root.getBoundingClientRect();let x=typeof state.x==='number'?state.x:b.ox+Math.max(4,(b.w-r.width)/2);let y=typeof state.y==='number'?state.y:b.oy+b.h-r.height-48;state.x=clamp(x,b.ox+4,b.ox+Math.max(4,b.w-r.width-4));state.y=clamp(y,b.oy+4,b.oy+Math.max(4,b.h-r.height-4));root.style.left=state.x+'px';root.style.top=state.y+'px';}
function mode(){return state.mode==='terminal'?'terminal':'editor';}
let lastEditor=null;
function activeEditor(){const focused=document.activeElement&&document.activeElement.closest('#monaco2')&&window.editor2?window.editor2:window.editor;if(focused)lastEditor=focused;return lastEditor||window.editor;}
function resetModifiers(){shift=false;ctrl=false;alt=false;syncModifiers();}
function updateMode(){root.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode());b.setAttribute('aria-pressed',String(b.dataset.mode===mode()));});root.querySelector('#fk-target').textContent=mode()==='terminal'?'TERMINAL':'EDITOR';render();save();}
function languageExtras(){if(mode()==='terminal')return['|','~','/','-','_','&&','./','Ctrl+C'];const lang=activeEditor()?.getModel()?.getLanguageId?.()||'';if(lang==='html')return['<','>','/','=', '"',"'",'{}','</>'];if(lang==='css'||lang==='scss')return['{','}',':',';','#','.','()','var()'];if(lang==='python')return[':', '_','()','[]','{}','#','=', '=>'];return['{','}','(',')','[',']','=>',';'];}
function keyLabel(label){if(label==='Backspace')return '⌫';if(label==='Delete')return 'Del';if(shifted[label]&&shift)return shifted[label];if(/[a-z]/.test(label)&&label.length===1&&(shift!==caps))return label.toUpperCase();return label;}
function render(){
 root.classList.toggle('fk-compact',!!state.compact);root.style.setProperty('--fk-height',clamp(Number(state.size)||38,30,52)+'px');
 const rows=[];
 if(state.numberRow)rows.push(['`','1','2','3','4','5','6','7','8','9','0','-','=','Backspace']);
 rows.push(['Tab','q','w','e','r','t','y','u','i','o','p','[',']','\\']);
 rows.push(['Caps','a','s','d','f','g','h','j','k','l',';','\'','Enter']);
 rows.push(['Shift','z','x','c','v','b','n','m',',','.','/','↑']);
 rows.push(['Ctrl','Alt','Esc','Home','←','↓','→','End','Delete','Space']);
 const short={undo:'↶',redo:'↷',save:'Simpan',run:'Jalan',find:'Cari',select:'Pilih',copy:'Salin',paste:'Tempel',cut:'Potong',comment:'//',duplicate:'Duplikat',moveup:'Baris ↑',movedown:'Baris ↓',clear:'Bersih',home:'Home',end:'End',tab:'Tab',esc:'Esc'};
 const fav=state.custom.map(v=>({action:v,label:short[v]||v,title:ACTIONS[v]||v}));rows.push([...fav,...languageExtras()]);
 keys.replaceChildren();
 for(const row of rows){const el=document.createElement('div');el.className='fk-row';for(const item of row){const key=document.createElement('button');key.type='button';key.className='fk-key';const label=typeof item==='string'?item:item.label,name=typeof item==='object'?item.title:label;key.textContent=keyLabel(label);key.dataset.key=typeof item==='string'?item:item.action;if(typeof item==='object')key.dataset.action=item.action;if(['Backspace','Delete','Enter','Shift','Caps','Ctrl','Alt','Tab','Home','End'].includes(name))key.classList.add('fk-wide');if(label==='Space')key.classList.add('fk-space');if(typeof item==='object')key.classList.add('fk-accent');key.setAttribute('aria-label',name);key.title=name;el.appendChild(key);}keys.appendChild(el);}
 root.querySelector('#fk-size').value=clamp(Number(state.size)||38,30,52);root.querySelector('#fk-size-label').textContent=root.querySelector('#fk-size').value+' px';root.querySelector('#fk-compact').checked=!!state.compact;root.querySelector('#fk-numbers').checked=!!state.numberRow;root.querySelector('#fk-haptic').checked=state.haptic!==false;syncModifiers();
}
const customs=root.querySelector('#fk-custom');
state.custom.forEach((v,i)=>{const select=document.createElement('select');select.setAttribute('aria-label','Tombol favorit '+(i+1));choices.forEach(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;select.appendChild(option);});select.value=v;select.onchange=()=>{state.custom[i]=select.value;save();render();};customs.appendChild(select);});
let shift=false,caps=false,ctrl=false,alt=false;
function syncModifiers(){keys.querySelectorAll('.fk-key').forEach(el=>{const k=el.dataset.key;el.classList.toggle('active',(k==='Shift'&&shift)||(k==='Caps'&&caps)||(k==='Ctrl'&&ctrl)||(k==='Alt'&&alt));if(!el.dataset.action)el.textContent=keyLabel(k);});}
function terminalKey(k){const input=document.querySelector('#term-input');if(!input)return;const start=input.selectionStart||0,end=input.selectionEnd||0;
 if(k==='Enter'||k==='↑'||k==='↓'){input.dispatchEvent(new KeyboardEvent('keydown',{key:k==='Enter'?'Enter':k==='↑'?'ArrowUp':'ArrowDown',bubbles:true,cancelable:true}));return;}
 if(k==='←'||k==='→'||k==='Home'||k==='End'){const pos=k==='Home'?0:k==='End'?input.value.length:clamp(k==='←'?start-1:end+1,0,input.value.length);input.setSelectionRange(pos,pos);input.focus({preventScroll:true});return;}
 if(k==='Backspace'||k==='Delete'){if(start===end&&((k==='Backspace'&&start===0)||(k==='Delete'&&end===input.value.length)))return;const a=start===end&&k==='Backspace'?Math.max(0,start-1):start,b=start===end&&k==='Delete'?Math.min(input.value.length,end+1):end;input.setRangeText('',a,b,'end');}
 else if(k==='Ctrl+C'||k==='Esc'){input.value='';input.setSelectionRange(0,0);}
 else input.setRangeText(k,start,end,'end');
 input.dispatchEvent(new Event('input',{bubbles:true}));input.focus({preventScroll:true});
}
function editorKey(k){const ed=activeEditor();if(!ed||!ed.getModel())return;const selection=ed.getSelection(),model=ed.getModel();if(!selection)return;
 if(['↑','↓','←','→','Home','End'].includes(k)){const pos=ed.getPosition();if(!pos)return;let line=pos.lineNumber,col=pos.column;if(k==='Home')col=1;else if(k==='End')col=model.getLineMaxColumn(line);else if(k==='↑'||k==='↓'){line=clamp(line+(k==='↑'?-1:1),1,model.getLineCount());col=clamp(col,1,model.getLineMaxColumn(line));}else if(k==='←'){if(col>1)col--;else if(line>1){line--;col=model.getLineMaxColumn(line);}}else if(col<model.getLineMaxColumn(line))col++;else if(line<model.getLineCount()){line++;col=1;}ed.setPosition({lineNumber:line,column:col});ed.revealPositionInCenterIfOutsideViewport({lineNumber:line,column:col});return;}
 if(k==='Esc'){ed.trigger('virtual-keyboard','closeFindWidget',null);return;}
 if(k==='Backspace'||k==='Delete'){if(selection.isEmpty()){const p=selection.getStartPosition();if(k==='Backspace'&&p.lineNumber===1&&p.column===1)return;if(k==='Delete'&&p.lineNumber===model.getLineCount()&&p.column===model.getLineMaxColumn(p.lineNumber))return;let a=p,b=p;if(k==='Backspace')a=p.column>1?{lineNumber:p.lineNumber,column:p.column-1}:{lineNumber:p.lineNumber-1,column:model.getLineMaxColumn(p.lineNumber-1)};else b=p.column<model.getLineMaxColumn(p.lineNumber)?{lineNumber:p.lineNumber,column:p.column+1}:{lineNumber:p.lineNumber+1,column:1};ed.executeEdits('virtual-keyboard',[{range:new monaco.Range(a.lineNumber,a.column,b.lineNumber,b.column),text:''}]);ed.setPosition(a);}else ed.executeEdits('virtual-keyboard',[{range:selection,text:''}]);return;}
 ed.trigger('virtual-keyboard','type',{text:k==='Enter'?'\n':k==='Tab'?'\t':k});
}
async function action(a){const ed=activeEditor(),terminal=mode()==='terminal';
 if(a==='run'){if(typeof runPreview==='function')runPreview();return;}if(a==='save'){if(typeof saveActive==='function')saveActive();return;}
 if(a==='clear'){if(terminal){document.querySelector('#term-input').value='';document.querySelector('#term-out').replaceChildren();try{localStorage.removeItem('cc_term_output');}catch(e){}}return;}
 if(a==='paste'){try{const text=await navigator.clipboard.readText();terminal?terminalKey(text):editorKey(text);}catch(e){if(typeof toast==='function')toast('Izinkan akses clipboard untuk menempel');}return;}
 if(a==='copy'||a==='cut'){const input=document.querySelector('#term-input'),sel=ed?.getSelection();const text=terminal?input.value.slice(input.selectionStart,input.selectionEnd):sel&&ed?.getModel()?.getValueInRange(sel);if(!text)return;try{await navigator.clipboard.writeText(text);}catch(e){if(typeof toast==='function')toast('Clipboard tidak tersedia');return;}if(a==='cut')terminal?terminalKey('Backspace'):editorKey('Backspace');return;}
 if(terminal){if(a==='select')document.querySelector('#term-input').select();else if(a==='home'||a==='end'||a==='tab'||a==='esc')terminalKey(({home:'Home',end:'End',tab:'\t',esc:'Esc'})[a]);return;}
 if(!ed)return;const ids={undo:'undo',redo:'redo',find:'actions.find',comment:'editor.action.commentLine',duplicate:'editor.action.copyLinesDownAction',moveup:'editor.action.moveLinesUpAction',movedown:'editor.action.moveLinesDownAction'};
 if(ids[a])ed.getAction(ids[a])?.run();else if(a==='select')ed.setSelection(new monaco.Range(1,1,ed.getModel().getLineCount(),ed.getModel().getLineMaxColumn(ed.getModel().getLineCount())));else if(a==='home'||a==='end')editorKey(a==='home'?'Home':'End');else if(a==='tab')editorKey('Tab');else if(a==='esc')editorKey('Esc');
}
function press(k,a){if(state.haptic!==false&&navigator.vibrate)navigator.vibrate(7);if(a){action(a);return;}if(['Shift','Caps','Ctrl','Alt'].includes(k)){if(k==='Shift')shift=!shift;if(k==='Caps')caps=!caps;if(k==='Ctrl')ctrl=!ctrl;if(k==='Alt')alt=!alt;syncModifiers();return;}
 if(ctrl&&k.toLowerCase()==='c'){if(mode()==='terminal')terminalKey('Ctrl+C');else action('copy');resetModifiers();return;}if(ctrl&&k.toLowerCase()==='v'){action('paste');resetModifiers();return;}if(ctrl&&k.toLowerCase()==='s'){action('save');resetModifiers();return;}if(ctrl&&k.toLowerCase()==='a'){action('select');resetModifiers();return;}if(alt&&(k==='↑'||k==='↓')&&mode()==='editor'){action(k==='↑'?'moveup':'movedown');resetModifiers();return;}
 let output=k==='Space'?' ':k;if(!['Esc','Enter','Tab','Backspace','Delete','Home','End','↑','↓','←','→'].includes(output)&&output.length===1){if(/[a-z]/i.test(output))output=shift!==caps?output.toUpperCase():output.toLowerCase();else if(shift)output=shifted[output]||output;}mode()==='terminal'?terminalKey(output):editorKey(output);if(shift||ctrl||alt)resetModifiers();
}
keys.addEventListener('pointerdown',e=>{if(e.target.closest('.fk-key'))e.preventDefault();});keys.addEventListener('click',e=>{const b=e.target.closest('.fk-key');if(b)press(b.dataset.key,b.dataset.action);});
root.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;resetModifiers();updateMode();}));root.querySelector('#fk-close').onclick=()=>toggleFloatingKeyboard(false);
root.querySelector('#fk-settings-button').onclick=()=>{const p=root.querySelector('#fk-settings');p.classList.toggle('show');root.querySelector('#fk-settings-button').setAttribute('aria-expanded',String(p.classList.contains('show')));requestAnimationFrame(place);};
root.querySelector('#fk-size').oninput=e=>{state.size=Number(e.target.value);render();place();save();};root.querySelector('#fk-compact').onchange=e=>{state.compact=e.target.checked;render();place();save();};root.querySelector('#fk-numbers').onchange=e=>{state.numberRow=e.target.checked;render();place();save();};root.querySelector('#fk-haptic').onchange=e=>{state.haptic=e.target.checked;save();};
const drag=root.querySelector('#fk-drag');let dragging=null;drag.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;e.preventDefault();dragging={id:e.pointerId,x:e.clientX,y:e.clientY,left:root.offsetLeft,top:root.offsetTop};drag.setPointerCapture(e.pointerId);});drag.addEventListener('pointermove',e=>{if(!dragging||dragging.id!==e.pointerId)return;state.x=dragging.left+e.clientX-dragging.x;state.y=dragging.top+e.clientY-dragging.y;place();});function endDrag(e){if(!dragging)return;try{if(drag.hasPointerCapture(e.pointerId))drag.releasePointerCapture(e.pointerId);}catch(err){}dragging=null;save();}drag.addEventListener('pointerup',endDrag);drag.addEventListener('pointercancel',endDrag);
window.toggleFloatingKeyboard=function(force){const visible=typeof force==='boolean'?force:!root.classList.contains('show');root.classList.toggle('show',visible);document.querySelector('#qt-keyboard-btn')?.setAttribute('aria-pressed',String(visible));if(visible){if(document.activeElement?.id==='term-input')state.mode='terminal';updateMode();requestAnimationFrame(place);}else save();};
document.addEventListener('focusin',e=>{if(e.target?.id==='term-input'&&root.classList.contains('show')){state.mode='terminal';updateMode();}else if(e.target?.closest?.('.monaco-editor')&&root.classList.contains('show')){state.mode='editor';updateMode();}});window.addEventListener('resize',()=>{if(root.classList.contains('show'))place();});window.visualViewport?.addEventListener('resize',()=>{if(root.classList.contains('show'))place();});updateMode();
})();
